language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.gradle

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH, TAG=$TRAVIS_TAG"
  - wget https://raw.githubusercontent.com/elastic/elasticsearch/v5.2.0/buildSrc/version.properties -O gradle.properties
  - ./gradlew clean check
